### ISSUE TITLE
Simplificando as condicionais

### ISSUE THREAD

**Issue by jorgevilaca82** [ingrlopes/java#1]
https://github.com/ingrlopes/java/blob/81a3b02e6db4b485025cf3b04fce4ca49d039ec7/ContaBanco/src/ContaTerminal.java#L37-L43

Olá Ingrid. Que tal melhorar o código nesse trecho simplificando as condições?

```java
char resposta = resultado.toLowerCase().charAt(0);

if (resposta == 's') {
  // caso resposta positiva
} 
else if (resposta == 'n') {
  // caso resposta negativa
}
```

**Comment by jorgevilaca82** [comment]
outra possibilidade é usar o método `startsWith` que verifica se uma string inicia de alguma forma.

```java
bool respondeuSim = resultado.toLowerCase().startsWith("s");

if (respondeuSim) {
}
else {
  // respondeu não
}

``´

**Comment by ingrlopes** [comment]
Obrigada pelas dicas, @jorgevilaca82 !

Já atualizei o meu código :)

**Comment by ingrlopes** [comment]
Obrigada pelas dicas, @jorgevilaca82 !

Já atualizei o meu código :)
